[package]
name = "image-dedup-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.7"
glob = "0.3.0"
image = "0.23.14"
img_hash = "3.2.0"
rayon = "1.5.1"
